On branch css-unclobber modified:   package.json Changed the test command to not include index.html in the glob. Previously running `npm test` resulted in an error:
/path/to/browserify-tape-spec/test/index.html:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
                                                              ^
SyntaxError: Unexpected token <